//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiuroPodrozyCzapeczka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atrakcja
    {
        public int IdAtrakcji { get; set; }
        public string NazwaAtrakcji { get; set; }
        public string AdresAtrakcji { get; set; }
        public Nullable<int> CenaAtrakcji { get; set; }
        public Nullable<int> IdZwiedzania { get; set; }
    
        public virtual Zwiedzanie Zwiedzanie { get; set; }
    }
}
