//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiuroPodrozyCzapeczka.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Czapeczka : DbContext
    {
        public Czapeczka()
            : base("name=Czapeczka")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atrakcja> Atrakcja { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Placowka> Placowka { get; set; }
        public virtual DbSet<Pokoj> Pokoj { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
        public virtual DbSet<Udzial> Udzial { get; set; }
        public virtual DbSet<Wycieczka> Wycieczka { get; set; }
        public virtual DbSet<Zwiedzanie> Zwiedzanie { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
