//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiuroPodrozyCzapeczka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiedniPracownicy
    {
        public int IdPracownika { get; set; }
        public int IdPlacowki { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
        public int pensja { get; set; }
    }
}
