//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiuroPodrozyCzapeczka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokoj
    {
        public int IdPokoju { get; set; }
        public int IdHotelu { get; set; }
        public int Liczba { get; set; }
        public Nullable<int> Cena { get; set; }
        public Nullable<int> Kaucja { get; set; }
        public Nullable<bool> Rezerwacja { get; set; }
        public Nullable<System.DateTime> WolnyData { get; set; }
        public Nullable<System.DateTime> KoniecWolnego { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
