//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiuroPodrozyCzapeczka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Udzial
    {
        public int IdUdzialu { get; set; }
        public int IdWycieczki { get; set; }
        public int IdKlienta { get; set; }
        public Nullable<int> IloscOsob { get; set; }
        public Nullable<int> Wplacone { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Wycieczka Wycieczka { get; set; }
    }
}
