//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiuroPodrozyCzapeczka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wycieczka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wycieczka()
        {
            this.Zwiedzanie = new HashSet<Zwiedzanie>();
            this.Udzial = new HashSet<Udzial>();
        }
    
        public int IdWycieczki { get; set; }
        public int IdPlacowki { get; set; }
        public int IdHotelu { get; set; }
        public string Panstwo { get; set; }
        public string Miasto { get; set; }
        public Nullable<System.DateTime> Datawycieczki { get; set; }
        public Nullable<int> Wydatki { get; set; }
        public Nullable<int> Cena { get; set; }
        public Nullable<System.DateTime> KoniecWycieczki { get; set; }
        public Nullable<System.DateTime> DataWplaty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zwiedzanie> Zwiedzanie { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual Placowka Placowka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Udzial> Udzial { get; set; }
    }
}
