//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiuroPodrozyCzapeczka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zwiedzanie
    {
        public int IdZwiedzania { get; set; }
        public int IdWycieczki { get; set; }
        public int IdAtrakcji { get; set; }
        public string Miasto { get; set; }
        public Nullable<int> CenaZwiedzania { get; set; }
        public Nullable<System.DateTime> DataZwiedzania { get; set; }
    
        public virtual Atrakcja Atrakcja { get; set; }
        public virtual Wycieczka Wycieczka { get; set; }
    }
}
