//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiuroPodrozyCzapeczka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zwiedzanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zwiedzanie()
        {
            this.Atrakcja = new HashSet<Atrakcja>();
        }
    
        public int IdZwiedzania { get; set; }
        public int IdWycieczki { get; set; }
        public string Miasto { get; set; }
        public Nullable<int> CenaZwiedzania { get; set; }
        public Nullable<System.DateTime> DataZwiedzania { get; set; }
    
        public virtual Wycieczka Wycieczka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atrakcja> Atrakcja { get; set; }
    }
}
